import type { Metadata } from "next"
import "./globals.css"
import { Merriweather_Sans, Bebas_Neue } from "next/font/google"
import { Navbar } from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const merriweather = Merriweather_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} antialiased bg-black`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
